# .github/workflows/push-docker.yml

name: Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  push_docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Download Docker image artifact from build
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.image_name }}
          path: /tmp

      - name: Load Docker image
        run: docker load -i /tmp/${{ inputs.image_name }}.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag ${{ inputs.image_name }}:${{ github.sha }} ${{ secrets.DOCKERHUB_REGISTRY_ID }}/${{ inputs.image_name }}:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_REGISTRY_ID }}/${{ inputs.image_name }}:${{ github.sha }}
