# .github/workflows/build-docker.yml

name: Build Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string

jobs:
  build_docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          tags: ${{ inputs.image_name }}:${{ github.sha }}
          outputs: type=docker, dest=/tmp/${{ inputs.image_name }}.tar

      - name: Upload Docker image to workspace
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image_name }}
          path: /tmp/${{ inputs.image_name }}.tar
